import codecs
with codecs.open('pagina.html', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    'Maana': 'Mañana',
    'MAANA': 'MAÑANA',
    'Matemticas': 'Matemáticas',
    'Matemtica': 'Matemática',
    'Matemǭticas': 'Matemáticas',
    'lgebra': 'Álgebra',
    '?lgebra': 'Álgebra',
    'Ingls': 'Inglés',
    'InglǸs': 'Inglés',
    'Fsica': 'Física',
    'Garca': 'García',
    'Prez': 'Pérez',
    'PǸrez': 'Pérez',
    'Sofa': 'Sofía',
    'Rodrguez': 'Rodríguez',
    'Luca': 'Lucía',
    'Martnez': 'Martínez',
    'Lpez': 'López',
    'Anala': 'Analía',
    'prximas': 'próximas',
    'prxima': 'próxima',
    'Prxima': 'Próxima',
    'aprobacin': 'aprobación',
    'ao': 'año',
    'estn': 'están',
    'estǭn': 'están',
    'est': 'está',
    'Poltica': 'Política',
    'Ciudadana': 'Ciudadanía',
    'participacin': 'participación',
    'Crsico': 'Córsico',
    'Filosofa': 'Filosofía',
    'Mircoles': 'Miércoles',
    'Mi': 'Mié',
    'Sbado': 'Sábado',
    'Qumica': 'Química',
    'Ramn': 'Ramón',
    'Toms': 'Tomás',
    'Ciruga': 'Cirugía',
    'Trmite': 'Trámite',
    'ltimas': 'últimas',
    'Describ': 'Describí',
    'justificacin': 'justificación',
    'Hac': 'Hacé',
    'arrastr': 'arrastrá',
    'aqu': 'aquí',
    'Contrasea': 'Contraseña',
    'Ingres': 'Ingresá',
    'Estadsticas': 'Estadísticas',
    'tendr': 'tendrá',
    'habr': 'habrá',
    'da': 'día',
    'das': 'días',
    'hbiles': 'hábiles',
    'mdica': 'médica',
    'mdico': 'médico',
    'Capacitacin': 'Capacitación',
    'Perodo': 'Período',
    'tipografa': 'tipografía',
    'TTULOS': 'TÍTULOS',
    '': '— ',    
    '\ufffd': '',
}

for k, v in replacements.items():
    text = text.replace(k, v)

with codecs.open('pagina.html', 'w', encoding='utf-8') as f:
    f.write(text)
